"""Add AuditLog table

Revision ID: cc089fc9d3b9
Revises: d1372b326633
Create Date: 2026-03-31 10:59:41.904702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc089fc9d3b9"
down_revision: Union[str, Sequence[str], None] = "d1372b326633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditlog",
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("client_ip", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("http_method", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("processing_time_ms", sa.Float(), nullable=False),
        sa.Column("action_name", sa.String(length=100), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auditlog_action_name"), "auditlog", ["action_name"], unique=False)
    op.create_index(op.f("ix_auditlog_actor_id"), "auditlog", ["actor_id"], unique=False)
    op.create_index(op.f("ix_auditlog_endpoint"), "auditlog", ["endpoint"], unique=False)
    op.create_index(op.f("ix_auditlog_http_method"), "auditlog", ["http_method"], unique=False)
    op.create_index(op.f("ix_auditlog_id"), "auditlog", ["id"], unique=False)
    op.create_index(op.f("ix_auditlog_is_deleted"), "auditlog", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_auditlog_resource_id"), "auditlog", ["resource_id"], unique=False)
    op.create_index(op.f("ix_auditlog_status_code"), "auditlog", ["status_code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auditlog_status_code"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_resource_id"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_is_deleted"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_id"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_http_method"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_endpoint"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_actor_id"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_action_name"), table_name="auditlog")
    op.drop_table("auditlog")
    # ### end Alembic commands ###
